import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import SubNavBar from '../components/SubNavBar'
import { faker } from "@faker-js/faker";
import OpenedMessage from '../components/OpenedMessage'
import Chat from '../components/Chat'
import { collection, collectionGroup, doc, getDoc, getDocs, onSnapshot, orderBy, query } from 'firebase/firestore';
import { auth, db } from '../firebase';
import StartChatModal from '../components/StartChatModal';
import { useEffect, useState } from 'react';


/*
chat = {
  cid: 100, 
  members: ["p1@gmail.com", "p2@gmail.com"]
  messages: [
    {
      from: 0,
      to: 1,
      text: "Hi How are you?",
      status: "Unread/Read",
      time: serverTime
    },
    {
      from: 1,
      to: 0,
      text: "I am fine",
      status: "Read/Unread",
      time: serverTime
    } 
  ]
}
*/

function Chats() {
  const [chatList, setChatList] = useState([]);
  const [openedChat, setOpenedChat] = useState([]);
  const openChat = async (chatID) => {
    const docRef = await getDoc(doc(db, `users/${auth.currentUser.uid}/chats`, chatID)).then(
      (docSnap) => {
        setOpenedChat(docSnap.data())
      }
    )
  }

  useEffect(
    () =>
      onSnapshot(
        query(collection(db, `users/${auth.currentUser.uid}/chats`)),
        (snapshot) => {
          setChatList(snapshot.docs);
        }
      ),
    []
  );
  console.log("ChatList: ", chatList)
  return (
      <div className="bg-default">
        <Head>
          <title>Task Management | Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        {/* Header */}
        <Header selectedTab="work" />
  
        {/* Tasks */}
        <div className='px-4 sm:px-6 md:px-8 lg:px-10 min-h-[75vh] lg:min-h-[85vh] pb-20'>
          <h1 className="text-3xl font-semibold mt-11">Chats</h1>
          <SubNavBar selectedTab="chats" />
          <div className="lg:grid lg:grid-cols-4 lg:gap-4 mt-5">
            <div className="bg-[#F4F5F8] py-5 px-3 rounded-lg lg:block min-h-[70vh]">
              <div className="flex justify-between items-center font-medium mb-3">
                <p>All Messages</p>
                <p className="text-xs">View all</p>
              </div>
              <StartChatModal openChat={openChat} />
              <div className="rounded-lg overflow-hidden">
                {chatList.map((chat)=>{
                  return <Chat chatDetails={chat.data()} key={chat.id} onClick={()=>openChat(chat.id)} />
                })}
              </div>
            </div>

            <div className="hidden lg:block bg-[#F4F5F8] rounded-lg col-span-3 py-5 px-3 min-h-[70vh]">
              {openedChat.length == 0 ? <div className='text-center text-gray-400'>No Opened Chat</div> : <OpenedMessage chatDetails={openedChat} />}
            </div>
          </div>
        </div>
        {/* Modal */}
      </div>
  )
}

export async function getServerSideProps(){
  var userList = []
  const users = query(collectionGroup(db, 'users'));
  const querySnapshot = await getDocs(users);
  querySnapshot.forEach((doc)=>{
    userList.push(JSON.parse(JSON.stringify(doc.data())))
  })
  return {
    props: {
      userList
    }
  }
}

export default Chats
