import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import SubNavBar from '../components/SubNavBar'
import { faker } from "@faker-js/faker";
import OpenedMessage from '../components/OpenedMessage'
import Chat from '../components/Chat'
import { collectionGroup, getDocs, query } from 'firebase/firestore';
import { db } from '../firebase';


/*
chat = {
  cid: 100, 
  members: ["p1@gmail.com", "p2@gmail.com"]
  messages: [
    {
      from: 0,
      to: 1,
      text: "Hi How are you?",
      status: "Unread/Read",
      time: serverTime
    },
    {
      from: 1,
      to: 0,
      text: "I am fine",
      status: "Read/Unread",
      time: serverTime
    } 
  ]
}
*/

function chats({userList}) {
  console.log(userList)
  const messages = [{}]
  return (
      <div className="bg-default">
        <Head>
          <title>Task Management | Admin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        {/* Header */}
        <Header selectedTab="work" />
  
        {/* Tasks */}
        <div className='px-4 sm:px-6 md:px-8 lg:px-10 min-h-[75vh] lg:min-h-[85vh]'>
          <h1 className="text-3xl font-bold mt-11">Chats</h1>
          <SubNavBar selectedTab="chats" />
          <div className="grid grid-cols-4 gap-4 mt-5">
            <div className="bg-[#F4F5F8] py-5 px-3 rounded-lg hidden lg:block min-h-[70vh]">
              <div className="flex justify-between items-center font-medium mb-3">
                <p>All Messages</p>
                <p className="text-xs">View all</p>
              </div>
              <div className="rounded-lg overflow-hidden">
                {userList.map((user)=>{
                  return <Chat sender={user.name} senderImage={user.image} messageTime="2:00" key={user.uid} />
                })}
              </div>
            </div>

            <div className="bg-[#F4F5F8] col-span-4 rounded-lg lg:col-span-3 py-5 px-3 min-h-[70vh]">
              <OpenedMessage />
            </div>
          </div>
        </div>
        {/* Modal */}
      </div>
  )
}

export async function getServerSideProps(){
  var userList = []
  const users = query(collectionGroup(db, 'users'));
  const querySnapshot = await getDocs(users);
  querySnapshot.forEach((doc)=>{
    userList.push(JSON.parse(JSON.stringify(doc.data())))
  })
  return {
    props: {
      userList
    }
  }
}

export default chats
