import React, { useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import SubNavBar from "../components/SubNavBar";
import Task from "../components/Task";
import TaskColumn from "../components/TaskColumn";
import Project from "../components/Project";
import { faker } from "@faker-js/faker";

function HomePage() {
  const [showOptions, setShowOptions] = useState(false);
  const [showUpdateOptions, setShowUpdateOptions] = useState(false);
  return (
    <div className="bg-default h-screen">
      <Head>
        <title>Task Management | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header selectedTab="work" />

      <div className="relative flex bg-gray-200">
        <button
          className="m-7 font-bold text-4xl"
          onMouseEnter={() => setShowOptions(true)}
        >
          ...
        </button>
        <div
          className={`absolute flex flex-col w-[150px] top-16 left-7 rounded bg-[#282828] ${
            showOptions ? null : "hidden"
          } text-white w-fit`}
          onMouseLeave={() => {
            setShowOptions(false)
            setShowUpdateOptions(false)
          }}
        >
          <button className="px-8 py-1 text-sm">View details</button>
          <button
            className="border-t border-white py-1 text-sm"
            onMouseEnter={() => setShowUpdateOptions(true)}
          >
            Update Status
          </button>
          <div className={`bg-[#282828] absolute left-[150px] top-[28px] w-[220px] ${showUpdateOptions ? null : "hidden"}`} onMouseLeave={()=>setShowUpdateOptions(false)}>
            <button className="px-5 py-1 text-sm w-[220px] text-start">Assigned</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">In Progress</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">Pending Client Review</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">Pending 3rd Party Action</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">Revision</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">Ready for review</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">Completed</button>
            <button className="px-5 py-1 text-sm w-[220px] text-start border-t border-white">Archive After 30 days</button>
          </div>
          <button className="border-t border-white py-1 text-sm">Attachments</button>
        </div>
      </div>
    </div>
  );
}

export default HomePage;
