import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Header from "../components/Header";
import Notification from "../components/Notification";
import { auth, db } from "../firebase";
import { Pagination } from "../utility/Pagination";

function Notifications() {
  const [notifList, setNotifList] = useState([]);
  const [currentPage, setCurrentPage] = useState(1);

  const perPage = 6;

  const indexOfLastData = currentPage * perPage;
  const indexOfFirstData = indexOfLastData - perPage;
  const currentData = notifList.slice(indexOfFirstData, indexOfLastData);

  const paginate = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  useEffect(
    () =>
      onSnapshot(
        query(collection(db, `users/${auth.currentUser.uid}/notifications`), orderBy("createdAt", "desc")),
        (snapshot) => {
          setNotifList(snapshot.docs);
          console.log(snapshot.d);
        }
      ),
    [db]
  );
  return (
    <div className="bg-default">
      <Head>
        <title>Task Management | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header selectedTab="settings" />

      <div className="px-4 sm:px-6 md:px-8 lg:px-10 min-h-[75vh] lg:min-h-[75vh] pb-20">
        <h1 className="text-3xl font-semibold mt-11 border-b-2 pb-5">
          Notifications
        </h1>
        {currentData.length != 0 ? (
          currentData.map((notif) => (
            <Notification notif={notif} key={notif.key} />
          ))
        ) : (
          <p>No Notifications</p>
        )}
        <div className="px-16 py-8">
          <Pagination
            perPage={perPage}
            totalData={notifList.length}
            paginate={paginate}
            currentPage={currentPage}
          />
        </div>
      </div>
    </div>
  );
}

export default Notifications;
