import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import Header from "../components/Header";
import { auth, db } from "../firebase";

function Notifications() {
  const [notifList, setNotifList] = useState([]);
  useEffect(
    () =>
      onSnapshot(
        query(
          collection(db, `users/${auth.currentUser.uid}/notifications`)
        ),
        (snapshot) => {
          setNotifList(snapshot.docs);
          console.log(snapshot.d)
        }
      ),
    [db]
  );
  console.log("Notificaitons:", notifList);
  return (
    <div className="bg-default">
      <Head>
        <title>Task Management | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header selectedTab="work" />

      <div className="px-4 sm:px-6 md:px-8 lg:px-10 min-h-[75vh] lg:min-h-[85vh] pb-20">
        <h1 className="text-3xl font-semibold mt-11">Notifications</h1>
        <div className="bg-[#F4F5F8] mt-5 pt-6 px-4 rounded-xl min-h-[60vh] lg:min-h-[65vh]">
          {notifList.length != 0 ? notifList.map((notif) => (
            <div key={notif.id}>{notif.data().title}</div>
          )):
          (
            <p>No Notifications</p>
          )
          }
        </div>
      </div>
    </div>
  );
}

export default Notifications;
