import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import Header from "../components/Header";
import SubNavBar from "../components/SubNavBar";
import Task from "../components/Task";
import TaskColumn from "../components/TaskColumn";

function ProjectTasks() {
  return (
    <div className="bg-default">
      <Head>
        <title>Task Management | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header selectedTab="work" />

      {/* Tasks */}
      <div className="px-4 sm:px-6 md:px-8 lg:px-10 min-h-screen">
        <h1 className="text-3xl font-semibold mt-11">Project Tasks</h1>
        <SubNavBar selectedTab="projects" />
        <div className="flex space-x-5 w-full overflow-x-scroll scroll-smooth scrollbar">
          <TaskColumn name="New Tasks">
            <Task name="App" priority="high" />
            <Task name="Logo" priority="low" />
          </TaskColumn>
          <TaskColumn name="To do" nCount="2">
            <Task
              name="Logo"
              priority="mid"
              commentCount="2"
              remainingTime="20hr.30min."
            />
            <Task
              name="Design"
              priority="low"
              taskStatus="assigned"
              remainingTime="20hr.30min."
            />
            <Task name="App" priority="high" />
          </TaskColumn>
          <TaskColumn name="In Progress">
            <Task name="Logo" priority="mid" />
            <Task name="App" priority="low" />
            <Task
              name="Design"
              priority="high"
              taskNumber="2"
              remainingTime="20hr.30min."
            />
          </TaskColumn>
          <TaskColumn name="Completed">
            <Task name="Design" priority="low" />
            <Task name="App" priority="high" taskNumber="2" />
            <Task name="Logo" priority="low" />
          </TaskColumn>
          <TaskColumn name="Pending Client Review">
            <Task name="Logo" priority="high" />
            <Task name="App" priority="low" />
            <Task name="Design" priority="high" taskNumber="2" />
          </TaskColumn>
          <TaskColumn name="Pending 3rd Party Action">
            <Task name="App" priority="high" />
            <Task name="Design" priority="high" />
            <Task name="Logo" priority="high" remainingTime="20hr.30min." />
          </TaskColumn>
          <TaskColumn name="Revision">
            <Task name="Logo" priority="mid" />
            <Task name="App" priority="low" />
            <Task name="Design" priority="high" />
          </TaskColumn>
          <TaskColumn name="Ready for review">
            <Task name="App" priority="high" />
            <Task name="Design" priority="mid" />
            <Task name="Logo" priority="low" />
          </TaskColumn>
        </div>
      </div>
      {/* Modal */}
    </div>
  );
}

export default ProjectTasks;
