import {
  collection,
  collectionGroup,
  doc,
  getDoc,
  getDocs,
  onSnapshot,
  orderBy,
  query,
  where,
} from "firebase/firestore";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Header from "../components/Header";
import SubNavBar from "../components/SubNavBar";
import Task from "../components/Task";
import TaskColumn from "../components/TaskColumn";
import { useAuth } from "../context/AuthContext";
import { auth, db } from "../firebase";

function QuickTasks({ taskList }) {
  const [tasks, setTasks] = useState([])
  useEffect(
    () =>
      onSnapshot(
        query(collection(db, `users/${auth.currentUser.uid}/tasks`), orderBy("name")),
        (snapshot) => {
          setTasks(snapshot.docs);
        }
      ),
    [db]
  );
  console.log("tasks: ",tasks);
  return (
    <div className="bg-default">
      <Head>
        <title>Task Management | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header selectedTab="work" />

      {/* Tasks */}
      <div className="px-4 sm:px-6 md:px-8 lg:px-10 min-h-screen">
        <h1 className="text-3xl font-bold mt-11">Quick Tasks</h1>
        <SubNavBar selectedTab="quicktasks" />
        <div className="flex space-x-5 w-full overflow-x-scroll h-[1000px] scroll-smooth scrollbar">

        </div>
      </div>
      {/* Modal */}
    </div>
  );
}

export async function getServerSideProps() {
  
  const tasks = await getDocs(query(collectionGroup(db, "users")));
  var taskList = [];
  tasks.forEach((doc)=>{
    taskList.push(JSON.parse(JSON.stringify(doc.data())))
  })
  return {
    props: {
      taskList
    },
  };
}

export default QuickTasks;
